name: Check PR
on:
  push:
    branches-ignore:
    - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'
    - name: install
      run: yarn install
    - name: build
      run: yarn build
    - name: lint
      run: yarn lint
