name: Deploy Master
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "::add-mask::${{ secrets.DEPLOY_SERVER_IP }}"
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'
    - run: yarn install
    - run: yarn build
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -vzr --delete-after --exclude="tiles/" --exclude="planets/"
        path: packages/frontend/build/
        remote_path:  ${{ secrets.DEPLOY_PATH }}
        remote_port:  ${{ secrets.DEPLOY_PORT }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
